### PR TITLE
Remove CSRF token management

### PR DESCRIPTION
**Pull request by rtfeldman**
Beginning in Elm 0.19, the current approach to CSRF token management will no longer work.

However, there is an easy solution: include [`csrf-xhr`](https://www.npmjs.com/package/csrf-xhr) on any pages that need CSRF token management, and this new version of `elm-rails` will continue to work as before!

### CODE REVIEW

**Comment by eeue56** [comment]
You (should) add documentation on how to set up the csrf-xhr package. This is a proper breaking change, since it fundementally changes how all requests in this package work

**Comment by rtfeldman** [comment]
Good call @eeue56 - added it to both README and to the docs!

**Review by stoeffel — APPROVED** [review]
looks great!

**Comment by rtfeldman** [comment]
Published as `7.0.0`!

**Pull request merged**
