### PR TITLE
Updated to elm 0.17

### PR DESCRIPTION
**Pull request by oakesja**
Updated all elm code to 0.17
Updated native code to new style for 0.17

### CODE REVIEW

**Comment by oakesja** [comment]
@rtfeldman Is there anything I can do to help move this forward?

**Comment by rtfeldman** [comment]
LGTM! @eeue56 want to take a look?

**Comment by scarfacedeb** [comment]
Any news on this one?

**Comment by eeue56** [comment]
seems fine

**Comment by eeue56** [comment]
@scarfacedeb @oakesja published as 4.0.2

**Pull request merged**
